baseurl = "./" #{{ .Site.BaseURL }} #"/" netlify #"./" local only #"https://hungry-wozniak-e915f8.netlify.com"
# baseurl = "https://relaxed-stonebraker-0c66a9.netlify.com/"
#relativeURLs = "true"

languageCode = "en-gb" #Initial configuration reset
#title = "Inspired Labs"
#disableKinds = ["home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]#"page",
#theme = "ultimate-simplicity"
#theme = "ga-hugo-theme"
## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  #new

[Params]
  [[Params.description]]
    description = "Scott Phillips is a Designer & Frontend Developer"

  [[Params.assignment]]
    assignment = "Designer & Frontend Developer"

  [[Params.location]]
    location = "Oxford"

  [[Params.links]]
    title = "Email"
    url = "mailto:alan.scott.phillips@pm.me"
