baseurl = "./" #{{ .Site.BaseURL }} #"/" netlify #"./" local only #"https://hungry-wozniak-e915f8.netlify.com"
#relativeURLs = "true"
#Change theme: `echo 'theme = "instantwebapp-vertical"' >> config.toml`
theme = "ga-hugo-theme" #pablo, instantwebapp-horizontal, ga-hugo-theme
languageCode = "en-gb" #Initial configuration reset
title = "instantWebapp"


copyright = "https://InspiredLabs.co.uk" # © = http://www.theukwebdesigncompany.com/articles/entity-escape-characters.php
#disableKinds = ["home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]#"page",
#theme = "ultimate-simplicity"
#theme = "ga-hugo-theme"
## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  #new

[Params]
author = "Alessandro Ronca"

  [[Params.description]]
    description = "Scott Phillips is a Designer & Frontend Developer"

  [[Params.assignment]]
    assignment = "Designer & Frontend Developer"

  [[Params.location]]
    location = "Oxford"

  [[Params.links]]
    title = "Email"
    url = "mailto:alan.scott.phillips@pm.me"
